test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    	args.enable_ldap = 0
		args.network_name = "ErgoYunohost"
		args.server_name = "ergo.yunohost"