#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

enable_ldap = false
network_name = "ErgoYunohost"
server_name =  "ergo.yunohost"

passwordhash=$(echo "$password"; echo "$password")

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir" --source_id=ldap

chmod +x "$install_dir/ergo"

# Copy help file
mkdir -p "$install_dir/help"
if test -e "$YNH_APP_BASEDIR/sources/help"; then
    cp --archive "$YNH_APP_BASEDIR/sources/help/." "$install_dir/help"
fi

_ynh_replace_vars "$install_dir/help/index.html"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="default.yaml" --destination="$install_dir/ircd.yaml"

ynh_config_add --template="ldap-config.yaml" --destination="$install_dir/ldap-config.yaml"

ynh_config_add --template="ircd.motd" --destination="$install_dir/ircd.motd"

#=================================================
# SET PASSWORD
#=================================================

pushd "$install_dir"
 	ynh_hide_warnings $install_dir/ergo genpasswd
popd

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

ynh_config_add_nginx
ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="A modern IRC server" --log="/var/log/$app/$app.log" --needs_exposed_ports=$port --needs_exposed_ports=$port_secure

#=================================================
# SPECIFIC SETUP
#=================================================

# adding the ergo dedicated user to the 'ssl-cert' group
# to permit the use of the Let's Encrypt certs
usermod -a -G ssl-cert "$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
