#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If enable_ldap doesn't exist, create it
ynh_app_setting_set_default --key=enable_ldap --value="$false"

# If network_name doesn't exist, create it
ynh_app_setting_set_default --key=network_name --value="ErgoYunohost"

# If server_name doesn't exist, create it
ynh_app_setting_set_default --key=server_name --value="ergo.yunohost"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="ircd.yaml, ldap-config.yaml, ircd.motd, help"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="A modern IRC server" --log="/var/log/$app/$app.log" --needs_exposed_ports=$port --needs_exposed_ports=$port_secure

#=================================================
# SPECIFIC SETUP
#=================================================

# adding the ergo dedicated user to the 'ssl-cert' group
# to permit the use of the Let's Encrypt certs
usermod -a -G ssl-cert "$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
